use super::{
    AppliedPolicyOverride, BaselineEntry, BaselineFile, DiffEntry, DiffReport, JsonReport,
    PolicyFile, PolicyOverride, WaiverEntry, WaiverFile, POLICY_SCHEMA_VERSION,
};
use crate::findings::{default_operational_contexts, Finding, OperationalContext, ThreatCategory};
use chrono::{DateTime, Utc};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::path::Path;

/// Stable identity hash for a finding, used by baseline/waiver matching.
///
/// The hash mixes only the fields that identify *which* finding this is:
/// `rule_id` + `artifact_path` + `match_value` + `matched_on`. We
/// deliberately exclude `reason` — it's a user-facing explanation that
/// can be reworded between scanner versions without the underlying
/// detection changing, so including it would silently invalidate every
/// baseline entry on every rule-message refresh.
///
/// **Breaking change note**: baselines generated by earlier versions of
/// skill-veil included `reason` in the hash. After upgrading to this
/// version, users must regenerate their baseline once (e.g. via
/// `skill-veil scan-package … --baseline new.json` then replacing the
/// old file). Re-scanning without regenerating will surface previously
/// suppressed findings as "new".
pub fn finding_fingerprint(finding: &Finding) -> String {
    let mut hasher = Sha256::new();
    hasher.update(finding.rule_id.as_bytes());
    hasher.update(b"\0");
    hasher.update(
        finding
            .artifact_path
            .as_deref()
            .unwrap_or_default()
            .as_bytes(),
    );
    hasher.update(b"\0");
    hasher.update(finding.match_value.as_bytes());
    hasher.update(b"\0");
    hasher.update(finding.matched_on.to_string().as_bytes());
    format!("{:x}", hasher.finalize())
}

#[must_use]
pub fn baseline_from_reports(reports: &[JsonReport]) -> BaselineFile {
    let entries = reports
        .iter()
        .flat_map(|report| report.findings.iter())
        .map(|finding| BaselineEntry {
            fingerprint: finding_fingerprint(finding),
            rule_id: finding.rule_id.clone(),
            artifact_path: finding.artifact_path.clone(),
            reason: finding.reason.clone(),
        })
        .collect();

    BaselineFile {
        schema_version: default_policy_schema_version(),
        entries,
    }
}

#[must_use]
pub fn apply_baseline(findings: Vec<Finding>, baseline: Option<&BaselineFile>) -> Vec<Finding> {
    let Some(baseline) = baseline else {
        return findings;
    };

    findings
        .into_iter()
        .filter(|finding| !finding_in_baseline(finding, baseline))
        .collect()
}

/// Count how many findings in the slice match a baseline entry.
/// Used to compute accurate suppression counts independently of application order.
///
/// NOTE: This assumes `apply_baseline` performs simple removal of matched findings.
/// If `apply_baseline` semantics change (e.g., to downgrade actions instead of removing),
/// this function must be updated to match.
#[must_use]
pub fn count_baseline_matches(findings: &[Finding], baseline: Option<&BaselineFile>) -> usize {
    let Some(baseline) = baseline else {
        return 0;
    };
    findings
        .iter()
        .filter(|finding| finding_in_baseline(finding, baseline))
        .count()
}

fn finding_in_baseline(finding: &Finding, baseline: &BaselineFile) -> bool {
    let fingerprint = finding_fingerprint(finding);
    baseline
        .entries
        .iter()
        .any(|entry| entry.fingerprint == fingerprint)
}

#[must_use]
pub fn apply_waivers(findings: Vec<Finding>, waivers: Option<&WaiverFile>) -> Vec<Finding> {
    let Some(waivers) = waivers else {
        return findings;
    };

    let now = Utc::now();
    findings
        .into_iter()
        .filter(|finding| {
            !waivers
                .waivers
                .iter()
                .any(|waiver| waiver_matches_finding(waiver, finding, now))
        })
        .collect()
}

#[must_use]
pub fn apply_policy_overrides(findings: Vec<Finding>, policy: Option<&PolicyFile>) -> Vec<Finding> {
    apply_policy_overrides_with_audit(findings, policy).0
}

fn match_override<'p>(
    finding: &Finding,
    overrides: &'p [PolicyOverride],
    now: DateTime<Utc>,
) -> Option<&'p PolicyOverride> {
    overrides
        .iter()
        .enumerate()
        .filter(|(_, po)| policy_override_matches(po, finding, now))
        .max_by_key(|(index, po)| (policy_override_specificity(po), *index))
        .map(|(_, po)| po)
}

fn build_audit_entry(
    finding: &Finding,
    po: &PolicyOverride,
    original_action: crate::findings::RecommendedAction,
) -> AppliedPolicyOverride {
    AppliedPolicyOverride {
        finding_fingerprint: finding_fingerprint(finding),
        rule_id: finding.rule_id.clone(),
        artifact_path: finding.artifact_path.clone(),
        override_id: po.id.clone(),
        original_action,
        effective_action: po.action,
        specificity: policy_override_specificity(po),
        reason: po.reason.clone(),
        matched_contexts: finding_contexts(finding),
    }
}

#[must_use]
pub fn apply_policy_overrides_with_audit(
    findings: Vec<Finding>,
    policy: Option<&PolicyFile>,
) -> (Vec<Finding>, Vec<AppliedPolicyOverride>) {
    let Some(policy) = policy else {
        return (findings, Vec::new());
    };

    let now = Utc::now();
    let mut audit = Vec::new();
    let findings = findings
        .into_iter()
        .map(|mut finding| {
            if let Some(po) = match_override(&finding, &policy.overrides, now) {
                let original_action = finding.recommended_action;
                // Policy overrides unconditionally replace the action, including
                // escalation (e.g., Log → Block). This is intentional for enterprise
                // use cases. The audit trail records both actions for full visibility.
                finding.recommended_action = po.action;
                audit.push(build_audit_entry(&finding, po, original_action));
            }
            finding
        })
        .collect();
    (findings, audit)
}

pub fn load_baseline(path: &Path) -> Result<BaselineFile, std::io::Error> {
    let content = std::fs::read_to_string(path)?;
    serde_json::from_str(&content)
        .or_else(|_| serde_yaml::from_str(&content))
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))
}

pub fn load_waivers(path: &Path) -> Result<WaiverFile, std::io::Error> {
    let content = std::fs::read_to_string(path)?;
    serde_json::from_str(&content)
        .or_else(|_| serde_yaml::from_str(&content))
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))
}

pub fn load_policy(path: &Path) -> Result<PolicyFile, std::io::Error> {
    let content = std::fs::read_to_string(path)?;
    let policy = serde_json::from_str(&content)
        .or_else(|_| serde_yaml::from_str(&content))
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))?;
    validate_policy(&policy)
        .map_err(|error| std::io::Error::new(std::io::ErrorKind::InvalidData, error))?;
    Ok(policy)
}

pub fn validate_policy(policy: &PolicyFile) -> Result<(), String> {
    if policy.schema_version != POLICY_SCHEMA_VERSION {
        return Err(format!(
            "Unsupported policy schema_version '{}', expected '{}'",
            policy.schema_version, POLICY_SCHEMA_VERSION
        ));
    }

    let mut seen = std::collections::HashSet::new();
    for policy_override in &policy.overrides {
        if policy_override.rule_id.is_none()
            && policy_override.artifact_path.is_none()
            && policy_override.context.is_none()
        {
            return Err(
                "Each policy override must define at least one selector: rule_id, artifact_path, or context"
                    .to_string(),
            );
        }
        if policy_override.reason.trim().is_empty() {
            return Err("Policy overrides must define a non-empty reason".to_string());
        }
        // Dedup key intentionally EXCLUDES `id`: that field is human
        // bookkeeping, not a semantic selector. Two overrides with the same
        // selectors + action but different ids are functionally duplicate;
        // `match_override`'s `max_by_key` would pick one arbitrarily, masking
        // the policy conflict. Keep `expires_at` in the key — different
        // expirations represent intentional time-bounded overrides.
        let key = format!(
            "{:?}|{:?}|{:?}|{:?}|{:?}",
            policy_override.rule_id,
            policy_override.artifact_path,
            policy_override.context,
            policy_override.expires_at,
            policy_override.action
        );
        if !seen.insert(key) {
            return Err("Duplicate policy override entries detected".to_string());
        }
    }

    Ok(())
}

pub fn validate_waivers(waivers: &WaiverFile) -> Result<(), String> {
    if waivers.schema_version != POLICY_SCHEMA_VERSION {
        return Err(format!(
            "Unsupported waiver schema_version '{}', expected '{}'",
            waivers.schema_version, POLICY_SCHEMA_VERSION
        ));
    }

    let mut seen = std::collections::HashSet::new();
    for waiver in &waivers.waivers {
        if waiver.rule_id.is_none() && waiver.artifact_path.is_none() && waiver.context.is_none() {
            return Err(
                "Each waiver must define at least one selector: rule_id, artifact_path, or context"
                    .to_string(),
            );
        }
        let key = format!(
            "{:?}|{:?}|{:?}|{:?}",
            waiver.rule_id, waiver.artifact_path, waiver.context, waiver.expires_at
        );
        if !seen.insert(key) {
            return Err("Duplicate waiver entries detected".to_string());
        }
    }

    Ok(())
}

#[must_use]
pub fn diff_reports(previous: &[JsonReport], current: &[JsonReport]) -> DiffReport {
    diff_reports_with_policy_state(previous, current, None, None)
}

#[must_use]
pub fn diff_reports_with_policy_state(
    previous: &[JsonReport],
    current: &[JsonReport],
    baseline: Option<&BaselineFile>,
    waivers: Option<&WaiverFile>,
) -> DiffReport {
    let now = Utc::now();
    let previous_map: HashMap<_, _> = previous
        .iter()
        .flat_map(|report| report.findings.iter())
        .map(|finding| (finding_fingerprint(finding), finding_to_diff_entry(finding)))
        .collect();

    let mut active_current = HashMap::new();
    let mut waived_findings = Vec::new();
    let mut baselined_findings = Vec::new();

    for finding in current.iter().flat_map(|report| report.findings.iter()) {
        let fingerprint = finding_fingerprint(finding);
        // Check waivers first, then baseline — matches scan_filter.rs ordering
        if waivers.is_some_and(|waiver_file| {
            waiver_file
                .waivers
                .iter()
                .any(|waiver| waiver_matches_finding(waiver, finding, now))
        }) {
            waived_findings.push(finding_to_diff_entry(finding));
            continue;
        }

        if baseline.is_some_and(|baseline_file| {
            baseline_file
                .entries
                .iter()
                .any(|entry| baseline_matches_finding(entry, finding))
        }) {
            baselined_findings.push(finding_to_diff_entry(finding));
            continue;
        }

        active_current.insert(fingerprint, finding_to_diff_entry(finding));
    }

    let new_findings = active_current
        .iter()
        .filter(|(fingerprint, _)| !previous_map.contains_key(*fingerprint))
        .map(|(_, entry)| entry.clone())
        .collect();

    // Build logical IDs from current active findings to detect "text-changed"
    // findings that are still logically present under a new fingerprint.
    let current_logical_ids =
        build_logical_ids(&active_current.values().cloned().collect::<Vec<_>>());

    // Logical IDs of findings suppressed by waivers or baselines.
    let suppressed_entries: Vec<DiffEntry> = waived_findings
        .iter()
        .chain(baselined_findings.iter())
        .cloned()
        .collect();
    let suppressed_logical_ids = build_logical_ids(&suppressed_entries);

    // A previous finding is "resolved" only if:
    // 1. Its exact fingerprint is NOT in current active (didn't survive unchanged)
    // 2. Its logical ID is NOT in current active (not still present with changed text)
    // 3. Its logical ID is NOT suppressed (not waived/baselined)
    let resolved_findings = previous_map
        .iter()
        .filter(|(fingerprint, _)| !active_current.contains_key(*fingerprint))
        .filter(|(_, entry)| !logical_id_matches(&current_logical_ids, entry))
        .filter(|(_, entry)| !logical_id_matches(&suppressed_logical_ids, entry))
        .map(|(_, entry)| entry.clone())
        .collect();
    let unchanged_findings = active_current
        .keys()
        .filter(|fingerprint| previous_map.contains_key(*fingerprint))
        .count();

    DiffReport {
        new_findings,
        resolved_findings,
        waived_findings,
        baselined_findings,
        unchanged_findings,
    }
}

/// Extracts logical identities (rule_id, artifact_path, category) from a slice of diff entries.
fn build_logical_ids(entries: &[DiffEntry]) -> Vec<(String, Option<String>, ThreatCategory)> {
    entries
        .iter()
        .map(|entry| {
            (
                entry.rule_id.clone(),
                entry.artifact_path.clone(),
                entry.category,
            )
        })
        .collect()
}

/// Checks whether a `DiffEntry`'s logical identity matches any entry in `ids`.
/// Uses suffix-based `paths_match` for consistency with waiver/baseline path matching.
fn logical_id_matches(ids: &[(String, Option<String>, ThreatCategory)], entry: &DiffEntry) -> bool {
    ids.iter().any(|id| {
        id.0 == entry.rule_id
            && id.2 == entry.category
            && match (&id.1, &entry.artifact_path) {
                (Some(pa), Some(pb)) => paths_match(pa, pb),
                (None, None) => true,
                _ => false,
            }
    })
}

pub(crate) fn default_policy_schema_version() -> String {
    POLICY_SCHEMA_VERSION.to_string()
}

/// Compare two artifact paths for logical equality.
///
/// Match a finding's `artifact_path` against a waiver / baseline / override
/// `artifact_path` field.
///
/// # Cross-package safety contract
///
/// Suffix matching is only allowed when the shorter (relative) path has
/// **at least 3 components**. Two-component paths like `"config/settings.py"`
/// silently suppressed findings across unrelated packages in monorepo /
/// dataset scans (e.g. a waiver authored for `/repo-a/config/settings.py`
/// would also suppress `/repo-b/config/settings.py`). Three components
/// gives reasonable specificity (`pkg/src/main.rs`) without forcing every
/// waiver to be fully qualified.
///
/// Absolute paths require exact equality — `Path::starts_with`/`ends_with`
/// on absolute paths makes the suffix semantic ambiguous. Users with
/// monorepo waiver needs should keep waivers absolute.
pub(crate) fn paths_match(a: &str, b: &str) -> bool {
    if a == b {
        return true;
    }
    let pa = std::path::Path::new(a);
    let pb = std::path::Path::new(b);
    if pa.is_absolute() && pb.is_absolute() {
        return false;
    }
    const MIN_RELATIVE_SUFFIX_COMPONENTS: usize = 3;
    let a_components = pa.components().count();
    let b_components = pb.components().count();
    if b_components >= MIN_RELATIVE_SUFFIX_COMPONENTS && pa.ends_with(pb) {
        return true;
    }
    if a_components >= MIN_RELATIVE_SUFFIX_COMPONENTS && pb.ends_with(pa) {
        return true;
    }
    false
}

pub(crate) fn waiver_matches_finding(
    waiver: &WaiverEntry,
    finding: &Finding,
    now: DateTime<Utc>,
) -> bool {
    if waiver.expires_at.is_some_and(|expires_at| expires_at < now) {
        return false;
    }

    let rule_matches = waiver
        .rule_id
        .as_ref()
        .is_none_or(|rule_id| rule_id == &finding.rule_id);
    let path_matches = waiver.artifact_path.as_ref().is_none_or(|path| {
        finding
            .artifact_path
            .as_ref()
            .is_some_and(|artifact_path| paths_match(artifact_path, path))
    });
    let context_matches = waiver
        .context
        .is_none_or(|context| finding_contexts(finding).contains(&context));

    rule_matches && path_matches && context_matches
}

pub(crate) fn baseline_matches_finding(entry: &BaselineEntry, finding: &Finding) -> bool {
    entry.fingerprint == finding_fingerprint(finding)
}

pub(crate) fn finding_to_diff_entry(finding: &Finding) -> DiffEntry {
    DiffEntry {
        fingerprint: finding_fingerprint(finding),
        rule_id: finding.rule_id.clone(),
        category: finding.category,
        artifact_path: finding.artifact_path.clone(),
        reason: finding.reason.clone(),
    }
}

pub(crate) fn policy_override_matches(
    policy_override: &PolicyOverride,
    finding: &Finding,
    now: DateTime<Utc>,
) -> bool {
    if policy_override
        .expires_at
        .is_some_and(|expires_at| expires_at < now)
    {
        return false;
    }

    let rule_matches = policy_override
        .rule_id
        .as_ref()
        .is_none_or(|rule_id| rule_id == &finding.rule_id);
    let path_matches = policy_override.artifact_path.as_ref().is_none_or(|path| {
        finding
            .artifact_path
            .as_ref()
            .is_some_and(|artifact_path| paths_match(artifact_path, path))
    });
    let context_matches = policy_override
        .context
        .is_none_or(|context| finding_contexts(finding).contains(&context));

    rule_matches && path_matches && context_matches
}

pub(crate) fn policy_override_specificity(policy_override: &PolicyOverride) -> usize {
    let mut specificity = 0_usize;
    if policy_override.rule_id.is_some() {
        specificity += 4;
    }
    if policy_override.artifact_path.is_some() {
        specificity += 2;
    }
    if policy_override.context.is_some() {
        specificity += 1;
    }
    specificity
}

#[must_use]
pub(crate) fn finding_contexts(finding: &Finding) -> Vec<OperationalContext> {
    if finding.operational_contexts.is_empty() {
        default_operational_contexts(finding.category, finding.artifact_kind)
    } else {
        finding.operational_contexts.clone()
    }
}

#[cfg(test)]
mod paths_match_tests {
    use super::paths_match;

    /// Contract: 2-component relative waivers do NOT cross package boundaries
    /// in a monorepo / dataset scan. Two-component paths silently suppressed
    /// findings across unrelated repos (e.g. a `config/settings.py` waiver
    /// authored for `repo-a` matched `repo-b/config/settings.py` too).
    #[test]
    fn paths_match_rejects_two_component_cross_package_match() {
        assert!(
            !paths_match("/repo-a/config/settings.py", "config/settings.py"),
            "2-component relative waivers MUST NOT span packages"
        );
        assert!(
            !paths_match("config/settings.py", "/repo-b/config/settings.py"),
            "symmetric: shorter side can't match a longer absolute path with only 2 components"
        );
    }

    /// 3+ components are specific enough to be considered a meaningful waiver
    /// path; suffix match still applies.
    #[test]
    fn paths_match_accepts_three_component_specific_suffix() {
        assert!(
            paths_match(
                "/some/dir/repo-a/config/settings.py",
                "repo-a/config/settings.py"
            ),
            "3-component relative path SHOULD suffix-match a longer absolute path"
        );
    }

    /// Two absolute paths require exact equality. Suffix matching on absolute
    /// paths is ambiguous and would let `/foo/bar` match `/baz/foo/bar`.
    #[test]
    fn paths_match_rejects_absolute_suffix_match() {
        assert!(!paths_match("/baz/foo/bar.py", "/foo/bar.py"));
    }

    /// Identical paths still match exactly.
    #[test]
    fn paths_match_exact_equality() {
        assert!(paths_match("a/b/c.py", "a/b/c.py"));
        assert!(paths_match("/abs/path", "/abs/path"));
    }

    #[test]
    fn paths_match_bare_filename_never_matches_across_dirs() {
        assert!(!paths_match("/repo/x/skill.md", "skill.md"));
    }
}

#[cfg(test)]
mod validate_policy_tests {
    use super::*;
    use crate::findings::RecommendedAction;
    use crate::policy::types::PolicyOverride;
    use crate::policy::POLICY_SCHEMA_VERSION;

    fn ov(id: Option<&str>, rule_id: Option<&str>, action: RecommendedAction) -> PolicyOverride {
        PolicyOverride {
            id: id.map(ToOwned::to_owned),
            rule_id: rule_id.map(ToOwned::to_owned),
            artifact_path: None,
            context: None,
            action,
            expires_at: None,
            reason: "test reason".to_string(),
        }
    }

    fn empty_policy() -> PolicyFile {
        PolicyFile {
            schema_version: POLICY_SCHEMA_VERSION.to_string(),
            overrides: Vec::new(),
            profiles: Default::default(),
        }
    }

    /// Contract: two overrides with the same SELECTORS but different `id`
    /// are duplicates. Including `id` in the dedup key let conflicting
    /// overrides slip past validation; `match_override`'s `max_by_key`
    /// would then pick one arbitrarily, hiding the conflict from the user.
    #[test]
    fn validate_policy_detects_duplicate_overrides_with_different_ids() {
        let mut policy = empty_policy();
        policy.overrides = vec![
            ov(Some("foo"), Some("RULE_A"), RecommendedAction::Block),
            ov(Some("bar"), Some("RULE_A"), RecommendedAction::Block),
        ];
        let result = validate_policy(&policy);
        assert!(
            result.is_err(),
            "Two overrides with identical selectors+action but different ids \
             MUST be flagged as duplicates"
        );
    }

    /// Different actions for the same selectors are NOT duplicates
    /// (intentional: a policy could differentiate `Log` vs `Block` by
    /// expiration window).
    #[test]
    fn validate_policy_accepts_different_actions_for_same_selectors() {
        let mut policy = empty_policy();
        policy.overrides = vec![
            ov(Some("a"), Some("RULE_A"), RecommendedAction::Block),
            ov(Some("b"), Some("RULE_A"), RecommendedAction::Log),
        ];
        assert!(validate_policy(&policy).is_ok());
    }
}
